apiVersion: batch/v1
kind: CronJob
metadata:
  name: post-observer
spec:
  schedule: "0 9 * * *" # 매일 오전 9시 (UTC 기준 확인 필요) 실행
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: post-observer
            image: gcr.io/프로젝트ID/post-observer:latest
            # 필요한 경우 환경변수 추가
            envFrom:
            - secretRef:
              name: jandi-secret
          restartPolicy: OnFailure # 실패 시 재시도