apiVersion: v1
kind: Service
metadata:
  name: frontend-service # [중요 1] 나중에 Ingress가 이 이름을 찾습니다.
spec:
  type: NodePort     # 외부 노출 없이 내부에서만 통신 (Ingress가 연결해줄 것이므로)
  selector:
    app: frontend   # [중요 2] Deployment의 라벨과 똑같아야 연결됨!
  ports:
    - protocol: TCP
      port: 80         # 서비스(가상 IP)의 포트 (보통 80 사용)
      targetPort: 8080 # 실제 파드(컨테이너)의 포트 (Deployment의 containerPort와 일치해야 함)