apiVersion: v1
kind: Secret
metadata:
  name: jandi-secret
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOjFxMnczZTRyIUAzNC4xNzMuMTMyLjY3OjU0MzIvamFuZGktZGI=
  FRONTEND_URL: Imh0dHA6Ly9sb2NhbGhvc3Q6ODAwMCI=
  JWT_SECRET: MmNkNTExNmEzYWI1MGVlMGJiMDNmYTQxN2ViMmYxMGY=
  RABBITMQ_HOST: YW1xcHM6Ly9zdnduZGx5ZzpBT2F6dDk3UWUyczZxSmZrV0FOQWNONzhScjNjeFdLQ0BtdXN0YW5nLnJtcS5jbG91ZGFtcXAuY29tL3N2d25kbHln
  REACT_APP_API_URL: aHR0cDovL2xvY2FsaG9zdDo4MDAw
  SMTP_PASSWORD: cXBldSB1aGt4IHNzcmogc2prZg==
  SMTP_SERVER: c210cC5nbWFpbC5jb20=
  SMTP_USER: bXllb25nanVnbzlAZ21haWwuY29tICMg7Jes6riwIOuplOydvCDri7Tri7ntlZjsi5zripQg67aE7J20IOyImOygle2VmOyLnOuptCDrkKnri4jri6Qg64KY7KSR7JeQIOuwsO2PrO2VoOuVjOuKlCBzZWNyZXTsnLzroZwg67CU6r+U7JW8IO2VoCDqsoMg6rCZ7JWE7JqUIQ==
  UPSTAGE_API_KEY: ICJ1cF9VU2MyUklzdjM4NFZ1NUZvUHpUa1p3d2Z3ZVlWZCI=