apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-server
  labels:
    app: main-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main-server
  template:
    metadata:
      labels:
        app: main-server
    spec:
      containers:
      - name: main-server
        image: asia-northeast3-docker.pkg.dev/calm-scarab-478705-c7/jandi-images-repo/main_server:latest # GKE 레지스트리 주소
        ports:
        - containerPort: 8080 
        envFrom:
        - secretRef:
            name: jandi-secret