apiVersion: v1
kind: Service
metadata:
  name: main-server-service 
spec:
  type: NodePort     
  selector:
    app: main-server  
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 8080 