apiVersion: v1
kind: Service
metadata:
  name: ai-server-service 
spec:
  type: ClusterIP     
  selector:
    app: ai-server   
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 8080 